import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Web3Modal from 'web3modal'
import { useState } from 'react'
import { ethers, Contract } from 'ethers'
import { TickDock_Contract_Address, TickDock_ABI } from '../utils/index'

let web3modal;

if(typeof(window)!=="undefined"){
  web3modal = new Web3Modal({
    network: "goerli",
    providerOptions: {},
    disableInjectedProvider: false
  })
}

export default function Home() {

  const [walletConnected,setWalletWalleted] = useState(false)

  const createEvent = async() => {
    try {
      const signer = await connectWallet(true)
      const TickDockContract = new Contract(TickDock_Contract_Address,TickDock_ABI,signer)
      const txn = await TickDockContract.addEvent()
      await txn.wait()
    } catch (error) {
      console.log(error)
    }
  }

  const connectWallet = async(needSigner=false) => {
    try {
      const instance = await web3modal.connect()
      const provider = new ethers.providers.Web3Provider(instance)
      const chainId = await provider.getNetwork()
      if(chainId!==5){
        window.alert("Please connect with Goerli test network!")
      }
      if(needSigner){
        const signer = provider.getSigner()
        setWalletWalleted(true)
        return signer
      }
      setWalletWalleted(true)
      return provider
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>TikDock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={connectWallet} >Connect Wallet</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
